variables:
    PROJECT: edde-framework

stages:
    - test
#    - compile
#    - package
    - deploy

test:
    stage: test
    script:
        - php bin/phpunit.phar --coverage-text --colors=never
    artifacts:
        name: $PROJECT-$CI_BUILD_REF_NAME-failed
        untracked: true
        when: on_failure

#compile:
#    stage: compile
#    script:
#        - php -d phar.readonly=off bin/compile.php
#    artifacts:
#        name: $PROJECT-$CI_BUILD_REF_NAME
#        paths:
#            - release/$PROJECT.phar
#    only:
#        - master
#        - tags
#        - /^\d+\.\d+$/

#package:
#    stage: package
#    script: /bin/true
#    dependencies:
#        - compile
#    artifacts:
#        name: $PROJECT-$CI_BUILD_REF_NAME.package
#        paths:
#            - release/$PROJECT.phar
#            - doc/
#            - src/
#    only:
#        - master
#        - tags
#        - /^\d+\.\d+$/

deploy:
    stage: deploy
    script:
#        - curl -X POST -F token=$PAGE_TOKEN -F ref=master $PAGE_TRIGGER
        - curl -X POST -F token=53839921cd8d3e4844a8203d3bedf9 -F ref=master https://edde-framework.org/api/v3/projects/edde%2Fedde-framework/trigger/builds
#    dependencies:
#        - compile
    only:
        - master
        - tags
        - /^\d+\.\d+$/
