variables:
    PROJECT: edde-framework

stages:
    - test
    - composer
    - review
    - staging
    - production

test:
    stage: test
    script:
        - php bin/composer.phar install
        - php bin/phpunit.phar --coverage-text --colors=never --exclude-group http
    artifacts:
        name: $PROJECT-$CI_BUILD_REF_NAME-failed
        untracked: true
        when: on_failure

composer:
    stage: composer
    script:
        - curl -X POST -F token=53839921cd8d3e4844a8203d3bedf9 -F ref=master https://edde-framework.org/api/v3/projects/4/trigger/builds
    only:
        - master
        - tags
        - /^\d+\.\d+$/

review:
    stage: review
    script:
        - php bin/composer.phar install
        - php bin/composer.phar exec phpunit -- --coverage-text --colors=never
    artifacts:
        name: $PROJECT-$CI_BUILD_REF_NAME-failed
        untracked: true
        when: on_failure
    environment:
        name: review/$CI_BUILD_REF_NAME
        url: https://$CI_ENVIRONMENT_SLUG.edde-framework.org:8080/
    except:
        - master

staging:
    stage: staging
    script:
        - echo 'staging'
    environment:
        name: staging
        url: https://staging.edde-framework.org:8080/
    only:
        - staging

production:
    stage: production
#    when: manual
    script:
        - echo 'production'
    environment:
        name: production
        url: https://edde-framework.org:8080/
    only:
        - master
