language: php
php:
    - '7.0'

before_script:
    - travis_retry composer update --no-interaction --prefer-dist $dependencies

after_success:
    - php -d phar.readonly=off bin/compile.php
    - composer execute sami -- --no-ansi update sami.conf.php

cache:
    directories:
        - $HOME/.composer/cache
