language: php
php:
    - '7.0'

before_script:
    - travis_retry composer update --no-interaction --prefer-dist $dependencies

after_success:
    - vendor/bin/test-reporter

cache:
    directories:
        - $HOME/.composer/cache
